### ISSUE TITLE
Can we use addresses instead of GPS coordinates?

### ISSUE THREAD

**Issue by cristianoccazinsp** [tschoffelen/react-native-map-link#125]
Hello,

Two questions:

- Still maintained?

- Can we use addresses instead of GPS coordinates? 

Thanks!

**Comment by tschoffelen** [comment]
Hi! Very much still maintained!

Addresses work for some of the apps this library integrates with, but not all of them unfortunately, nor does it always lead to the expected result, which is why  passing in coordinates is the standard way to use this library.

There's some really nice geocoding APIs you can utilise if you want to get latitude and longitude pairs based on an address, but that falls outside the scope of this library.

**Comment by Noitidart** [comment]
For the main ones like google and apple maps does address work? Those are the only ones I was offering.
